/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserManagement;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 *
 * @author Shubham
 */
public class Credentials extends javax.swing.JFrame {
  
    /**
     * Creates new form Credentials
     */
    String name,

    /**
     * Creates new form Creds
     */

    /**
     * Creates new form Credentials
     */
    dateOfBirth,

    /**
     * Creates new form Creds
     */

    /**
     * Creates new form Credentials
     */
    address,

    /**
     * Creates new form Creds
     */

    /**
     * Creates new form Credentials
     */
    email;
    ResultSet rs1,rs2;
    String message;
    
    static String JDBC_DRIVER;  
    static String DB_URL;
    static String USER;
    static String PASS;
    Connection conn;
    Statement stmt1,stmt2;
    public Credentials(String n,String dob,String add,String em) {
        initComponents();
        
        this.setTitle("Sign Up!");
        message = "";
        
        name = n;
        dateOfBirth = dob;
        address = add;
        email = em;
        
        
        try
        {
            JDBCConnections ob1 = new JDBCConnections("SELECT * FROM personalinfo","userdetails");
            rs1 = ob1.rs;
            rs1.beforeFirst();
            JDBCConnections ob2 = new JDBCConnections("SELECT * FROM credentials","userdetails");
            rs2 = ob2.rs;
            rs2.beforeFirst();
        }
        catch(Exception e2)
        {
             System.out.println("10");
            System.out.println(e2) ;
        }
        this.setLocationRelativeTo(null) ; 
    }
    public boolean validateData(String user,String pass)
    {
        if(user.equals("")||pass.equals(""))
        {
            message = "Empty username or password";
            return false;
        }
        else if (pass.length()<8)
        {
            message="The password length should be greater than or equal to 8 characters";
            return false;
        }
        else
        {
            try
            {
                while(rs2.next())
                {
                    String User = rs2.getString("Username");
                    if(User.equals(user))
                    {
                        message = "Username already exists! Choose another!";
                        return false;
                    }
                }
            }
            catch(Exception e2)
            {
                System.out.println(e2);
            }
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();
        sign_in = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Signing you up! ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 30, 260, 44);

        user_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        user_field.setToolTipText("SSSD");
        user_field.setBorder(new javax.swing.border.MatteBorder(null));
        user_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(user_field);
        user_field.setBounds(250, 120, 190, 19);

        pass_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pass_field.setToolTipText("SSDDF");
        pass_field.setBorder(new javax.swing.border.MatteBorder(null));
        pass_field.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(pass_field);
        pass_field.setBounds(250, 170, 188, 19);

        sign_in.setBackground(new java.awt.Color(51, 255, 0));
        sign_in.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sign_in.setText("Submit");
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel2.add(sign_in);
        sign_in.setBounds(120, 230, 71, 25);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(310, 230, 53, 25);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Enter Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 120, 92, 17);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Enter Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 180, 87, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/architecture-background-blue-633520.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 20, 510, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/highwall36.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_fieldActionPerformed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
            String user = user_field.getText();
            String pass = pass_field.getText();
            
            boolean check = validateData(user,pass);
            if(check==false)
            {
                Message ob = new Message("ERROR!",message,sign_in);
                new Credentials(name,dateOfBirth,address,email).setVisible(true) ;
            }
            else
            {
                message = "Sign Up Successful!";
                Message ob = new Message("SUCCESS!",message,sign_in);
                try
                {
                    rs1.moveToInsertRow();
                    rs1.updateString("Name",name);
                    rs1.updateString("DateOfBirth",dateOfBirth);
                    rs1.updateString("Address",address);
                    rs1.updateString("Email",email);
                    rs1.updateString("Username", user);
                    System.out.println("1");
                    rs1.insertRow();
                    System.out.println("2");
                    rs1.beforeFirst();
                    //
                    System.out.println("3");
            
                    rs2.moveToInsertRow();
                    System.out.println("4");
                    rs2.updateString("Username",user);
                    rs2.updateString("Password",pass);
                    rs2.insertRow();
                    System.out.println("5");
                    rs2.beforeFirst();
                    System.out.println("6");
                    //rs1.insertRow();
                    //rs2.insertRow();
                    rs1.close();
                    rs2.close();
                }
                catch(Exception e1)
                {
                    System.out.println(e1);
                }
                this.dispose();
                new SignIn().setVisible(true);
            }
        
        dispose() ;    
               // TODO add your handling code here:
    }//GEN-LAST:event_sign_inActionPerformed
  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose() ;
         new MainScreen().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void user_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_fieldActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credentials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credentials("Shubham","1997/06/18","Pitambara puri","shubham234727@gmail.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField user_field;
    // End of variables declaration//GEN-END:variables
}
