/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserManagement;


import HotelManagement.EnterDetailsGUI;
import java.sql.ResultSet;

/**
 *
 * @author Shubham
 */
public class SignIn extends javax.swing.JFrame {
    String message;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        this.setTitle("Login page");
        message = "Login Successful!";
        
        this.setTitle("Login page");
        initComponents();
        this.setLocationRelativeTo(null) ; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();
        sign_in = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(210, 30, 98, 44);

        user_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        user_field.setToolTipText("Enter username");
        user_field.setBorder(new javax.swing.border.MatteBorder(null));
        user_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(user_field);
        user_field.setBounds(250, 120, 190, 19);

        pass_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pass_field.setToolTipText("Enter password");
        pass_field.setBorder(new javax.swing.border.MatteBorder(null));
        pass_field.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pass_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(pass_field);
        pass_field.setBounds(250, 170, 188, 19);

        sign_in.setBackground(new java.awt.Color(51, 255, 0));
        sign_in.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        sign_in.setText("Submit");
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        jPanel2.add(sign_in);
        sign_in.setBounds(120, 230, 71, 25);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(310, 230, 53, 25);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Enter Username");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 120, 92, 17);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Enter Password");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 180, 87, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/e8f11ac46c12630bc00cc2a4b3c64fb7.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 20, 510, 300);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/highwall7.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean validateCredentials(String username,String password)
    {
        if(username.equals("")||password.equals(""))
        {
            message = "Empty username or password!";
            return false;
        }
            
        boolean fl = false;
        
        try
        {
            JDBCConnections ob = new JDBCConnections("SELECT * from credentials","userdetails");
            ResultSet r = ob.rs;
        
            while(r.next())
            {
                String user_name = r.getString("Username");
                String pass = r.getString("Password");
                if(user_name.equals(username)&&pass.equals(password))
                {
                    fl = true;
                    return fl;
                }
            }
            message = "Invalid username and/or password!";
            return fl;
        }
        catch(Exception e4)
        {
            System.out.println(e4);
            return false;
        }
    }
    private void pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_fieldActionPerformed

    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
    String user = user_field.getText();
            String pass = pass_field.getText();
            boolean check = validateCredentials(user,pass);
            if(check==false)
            {
                user_field.setText("");
                pass_field.setText("");
                Message ob = new Message("ERROR!",message,sign_in);
                new SignIn().setVisible(true) ;
            }
            else
            {
                message = user;
                Message ob = new Message("SUCCESS!",message,sign_in);
                new InterScreen(message).setVisible(true) ;// Link to Part2
            }
        
        dispose() ;    
               // TODO add your handling code here:
    }//GEN-LAST:event_sign_inActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose() ;
         new MainScreen().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void user_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_fieldActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField user_field;
    // End of variables declaration//GEN-END:variables
}
