/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserManagement;

;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Shubham
 */
public class SignUp extends javax.swing.JFrame {
String message ;
    /**
     * Creates new form Portal
     */
    public SignUp() {
        
        initComponents();
        this.setLocationRelativeTo(null) ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        submit_signup = new javax.swing.JButton();
        back_signup = new javax.swing.JButton();
        address_field = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 460));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(209, 18, 108, 44);

        name_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        name_field.setToolTipText("Enter name");
        name_field.setBorder(new javax.swing.border.MatteBorder(null));
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(name_field);
        name_field.setBounds(227, 98, 265, 19);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(68, 99, 38, 17);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Date of Birth:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(68, 135, 77, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Residential Address:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(68, 169, 113, 17);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("E-mail Address:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(68, 199, 86, 17);

        email_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        email_field.setToolTipText("Enter e-mail");
        email_field.setBorder(new javax.swing.border.MatteBorder(null));
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(email_field);
        email_field.setBounds(227, 199, 265, 19);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(4, 250, 532, 11);

        submit_signup.setBackground(new java.awt.Color(51, 255, 0));
        submit_signup.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        submit_signup.setText("Submit");
        submit_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_signupActionPerformed(evt);
            }
        });
        jPanel1.add(submit_signup);
        submit_signup.setBounds(110, 350, 71, 25);

        back_signup.setBackground(new java.awt.Color(255, 0, 0));
        back_signup.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        back_signup.setText(" Back ");
        back_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_signupActionPerformed(evt);
            }
        });
        jPanel1.add(back_signup);
        back_signup.setBounds(360, 350, 65, 25);

        address_field.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        address_field.setToolTipText("Enter address");
        address_field.setBorder(new javax.swing.border.MatteBorder(null));
        address_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(address_field);
        address_field.setBounds(227, 167, 265, 20);

        jDateChooser1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(230, 130, 260, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/abstract-background-25.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 550, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 551, 389);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/highwall7.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 600, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean validateData(String name,String date,String address,String email)
    {
      
        if(name.equals("")||address.equals("")||email.equals(""))
        {
            message = "One or more empty fields!";
            name_field.setText("");
            address_field.setText("");
            email_field.setText("");
            return false;
        }
        String regex = "^[\\w!#$%&'*+/=?`{|}~^-]+(?:\\.[\\w!#$%&'*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
      Pattern pattern = Pattern.compile(regex);
        boolean fl = false;
        
        for(int i=0;i<email.length();i++)
        { Matcher matcher = pattern.matcher(email);
         
            if(matcher.matches())
            {
                fl = true;
                break;
            }
        }
        
        if(fl==true)
            return true;
        else
        {
            message = "Invalid E-mail ID!";
            email_field.setText("");
            return false;
        }
        
    }
    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void submit_signupActionPerformed(java.awt.event.ActionEvent evt)  {//GEN-FIRST:event_submit_signupActionPerformed
    try {
        String name,dateOfBirth,address,email;
        name = name_field.getText();
        String date = "2016/08/06";
        java.util.Date date2 = new SimpleDateFormat("yyyy/MM/dd").parse(date);
        jDateChooser1.setDate(date2);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
        dateOfBirth=sdf.format(jDateChooser1.getDate());
        address=address_field.getText() ;
        email=email_field.getText() ;
        boolean fl = validateData(name,dateOfBirth,address,email);
        if(fl==false)
        {
            Message ob = new Message("ERROR!",message,submit_signup);
        }
        else
        {
            message = "Registration successful! Proceed to select username and password.";
            Message ob = new Message("CONTINUE!",message,submit_signup,name_field.getText(),sdf.format(jDateChooser1.getDate()),address_field.getText(),email_field.getText());
            this.dispose();
        }
        
        // TODO add your handling code here:
    } catch (ParseException ex) {
        Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_submit_signupActionPerformed



    private void back_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_signupActionPerformed
                
        dispose() ;
        new MainScreen().setVisible(true) ;      // TODO add your handling code here:
    }//GEN-LAST:event_back_signupActionPerformed

    private void address_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_fieldActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_field;
    private javax.swing.JButton back_signup;
    private javax.swing.JTextField email_field;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name_field;
    private javax.swing.JButton submit_signup;
    // End of variables declaration//GEN-END:variables
}
