package HotelManagement;
import UserManagement.JDBCConnections;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.regex.Pattern;

public class BookHotel extends javax.swing.JFrame {

    JDBCConnections ob,ob2;
    String username,location,hotelname,roomtype;
    int rooms;
    Date Checkin,Checkout;
    String adhaar;
    String pancard;
    Date date;
    ResultSet RS3,RS4;
    // Stores the current date that is the date on which the booking was made!
    HotelParticularGUI obj;
    public BookHotel(HotelParticularGUI o,String username,int rooms,String location,String hotelname,Date checkin,Date checkout,String roomtype) {
        initComponents();
        obj = o;
        adhaar = "";
        pancard = "";
        this.username = username;
        this.rooms = rooms;
        this.location = location;
        this.hotelname = hotelname;
        Checkin = checkin;
        Checkout = checkout;
        this.roomtype = roomtype;
        ob = new JDBCConnections("SELECT * FROM bookinglist","hoteldetails");
        ob2 = new JDBCConnections("SELECT * FROM hotellist","hoteldetails");
        this.setLocationRelativeTo(null);
        obj.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter ADHAAR/PANCARD number");
        setMaximumSize(new java.awt.Dimension(690, 388));
        setMinimumSize(new java.awt.Dimension(690, 388));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.MatteBorder(null));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(138, 210, 427, 30);

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 328, 127, 30);

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(371, 328, 134, 30);

        jComboBox1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adhaar UID", "PAN card number" }));
        jComboBox1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 120, 427, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setText("Confirm Booking");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(225, 27, 247, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/abstract-architecture-attractive-988873.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean validateID(String id)
    {
        if(jComboBox1.getSelectedItem().equals("Adhaar UID"))
        {
            // Introduce the check that it is a 12 digit number only!
            Pattern pattern = Pattern.compile("\\d{12}");
            if(pattern.matcher(id).matches())
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        else
        {
            Pattern pattern = Pattern.compile("([A-Z]{5})(\\d{4})([A-Z])");
            if(pattern.matcher(id).matches())
                return true;
            else 
                return false;
        }
    }
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = jTextField1.getText();
        boolean fl = validateID(id);
        if(fl==false)
        {
            new ErrorDialog("Wrong " + jComboBox1.getSelectedItem() + " entered!");
        }
        else
        {
             /* means entered ID is valid,now enter details in booking database, update roomcount in hotellist
            and generate a booking reference number for the user!*/
            /*We're not allowing one user to have multiple bookings in his name!*/
            // First update roomcount in hotellist portal
            try
            {
            RS3 = ob2.rs;
            while(RS3.next())
            {
                if(RS3.getString("name").equals(hotelname)&&RS3.getString("city").equals(location))
                {
                    int presentroomcount = RS3.getInt("roomcount");
                    int newroomcount = presentroomcount-rooms;
                    RS3.updateInt("roomcount",newroomcount);
                    RS3.updateRow();
                    break;
                }
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
            ResultSet RS4 = ob.rs;
            date = new Date();// holds current date i.e date of booking
            int c = 0;
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
            try
            {
                RS4.beforeFirst();
                RS4.moveToInsertRow();
                RS4.updateString("username",username);
                RS4.updateString("location",location);
                RS4.updateString("hotelname",hotelname);
                RS4.updateString("checkin",dateFormat.format(Checkin));
                RS4.updateString("checkout",dateFormat.format(Checkout));
                RS4.updateInt("rooms",rooms);
                RS4.updateString("roomtype",roomtype);
                RS4.updateString("bookingdate",dateFormat.format(date));
                RS4.updateString("idtype",jComboBox1.getSelectedItem().toString());
                RS4.updateString("id",id);
                RS4.insertRow();
                
                // Check for booking reference number must be shown!!
                ob = new JDBCConnections("SELECT * FROM bookinglist where username = '"+username+"'","hoteldetails");
                ResultSet rs = ob.rs;
                rs.afterLast();
                rs.previous();
                new MessageDialog(jButton2,"BookHotel","SUCCESS!","Booking successfully completed!Your booking reference number is: "+ rs.getInt("bookingrefnumber"));
              
                RS3.close();
                RS4.close();
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookHotel().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
