/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelManagement;

import UserManagement.JDBCConnections;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Shubham
 */
public class Modification extends javax.swing.JFrame {
static String booking ;
    /**
    
     */
    public Modification(String t) {
        booking=t ;
        initComponents();
        this.setLocationRelativeTo(null) ; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        checkin = new com.toedter.calendar.JDateChooser();
        checkout = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(686, 463));
        setMinimumSize(new java.awt.Dimension(686, 463));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setText("Modification Portal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(207, 33, 288, 44);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("New Check in Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(165, 175, 106, 17);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("New Checkout Date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(165, 271, 112, 20);
        getContentPane().add(checkin);
        checkin.setBounds(386, 172, 160, 20);
        getContentPane().add(checkout);
        checkout.setBounds(386, 271, 160, 20);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(311, 368, 71, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserManagement/Images/architecture-background-blue-633520.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 690, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 boolean validateData(Date checkin,Date checkout,String bookrefno)
        {
            if(checkin==null||checkout==null||bookrefno.equals(""))
            {
               return false;
            }
            return true;
        }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        
        Date check_in = checkin.getDateEditor().getDate();
        
        Date check_out = checkout.getDateEditor().getDate();
        
        boolean fl = validateData(check_in,check_out,booking);
        if(fl==false)
        {
            new ErrorDialog("One or more fields empty!");
        }
        else
        {
            
            try{
                JDBCConnections obj = new JDBCConnections("SELECT * FROM bookinglist","hoteldetails");
                ResultSet RS = obj.rs;
                validateData(check_in,check_out,booking);
                try
                {
                    int bookrefno = Integer.parseInt(booking);
                    while(RS.next())
                    {
                        if(RS.getInt("bookingrefnumber")==bookrefno)
                        {
                            RS.updateString("checkin",dateFormat.format(check_in));
                            RS.updateString("checkout",dateFormat.format(check_out));
                            RS.updateRow();
                            break;
                        }
                    }
                }
                catch(NumberFormatException e)
                {
                    new ErrorDialog("Please enter a positive integer!");
                }
                catch(Exception e){}
                new ErrorDialog("Your Checkin and Checkout dates have succesfully updated");
                
            }catch(Exception e){
                
            }
            finally{
                this.setVisible(false);
            }
            
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modification(booking).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser checkin;
    private com.toedter.calendar.JDateChooser checkout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
